[project]
name = "3 CANDLE ALGO"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "pyotp>=2.9.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "websocket-client>=1.9.0",
]


